#!/bin/bash
# Google Search Console URL Submission Script
# This script provides URLs to submit to Google Search Console
# Since GSC requires authentication, this generates the submission commands

echo "=========================================="
echo "Google Search Console URL Submission"
echo "=========================================="
echo ""
echo "Submit these URLs for indexing in Google Search Console:"
echo ""
echo "1. Things To Do (Updated)"
echo "   https://pagosaforestlodge.com/things-to-do/"
echo ""
echo "2. Tours & Excursions Guide (New)"
echo "   https://pagosaforestlodge.com/blog/pagosa-springs-tours-excursions-guide-2026/"
echo ""
echo "3. Ice Skating Guide (New)"
echo "   https://pagosaforestlodge.com/blog/ice-skating-pagosa-springs-guide-2026/"
echo ""
echo "4. Kids Activities Guide (Fixed Image)"
echo "   https://pagosaforestlodge.com/blog/things-to-do-pagosa-springs-kids/"
echo ""
echo "=========================================="
echo "Manual Submission Instructions:"
echo "=========================================="
echo ""
echo "Option 1: Google Search Console Web Interface"
echo "----------------------------------------------"
echo "1. Visit: https://search.google.com/search-console"
echo "2. Select property: pagosaforestlodge.com"
echo "3. Go to 'URL Inspection' in left sidebar"
echo "4. Enter each URL above"
echo "5. Click 'Request Indexing' for each"
echo ""
echo "Option 2: URL Inspection Tool Direct Links"
echo "-------------------------------------------"
echo "Visit these URLs (requires GSC login):"
echo ""
echo "Things To Do:"
echo "https://search.google.com/search-console/inspect?resource_id=https://pagosaforestlodge.com/&id=https://pagosaforestlodge.com/things-to-do/"
echo ""
echo "Tours Guide:"
echo "https://search.google.com/search-console/inspect?resource_id=https://pagosaforestlodge.com/&id=https://pagosaforestlodge.com/blog/pagosa-springs-tours-excursions-guide-2026/"
echo ""
echo "Ice Skating:"
echo "https://search.google.com/search-console/inspect?resource_id=https://pagosaforestlodge.com/&id=https://pagosaforestlodge.com/blog/ice-skating-pagosa-springs-guide-2026/"
echo ""
echo "Kids Guide:"
echo "https://search.google.com/search-console/inspect?resource_id=https://pagosaforestlodge.com/&id=https://pagosaforestlodge.com/blog/things-to-do-pagosa-springs-kids/"
echo ""
echo "=========================================="
echo "Sitemap Submission"
echo "=========================================="
echo ""
echo "Also resubmit your sitemap:"
echo "https://search.google.com/search-console/sitemaps?resource_id=https://pagosaforestlodge.com/"
echo ""
echo "Sitemap URL: https://pagosaforestlodge.com/sitemap.xml"
echo ""
echo "=========================================="
echo "Expected Timeline"
echo "=========================================="
echo ""
echo "• Indexing: 1-3 days"
echo "• Ranking changes: 2-4 weeks"
echo "• Traffic impact: 4-8 weeks"
echo ""
