#!/bin/bash
# Google Search Console URL Submission Script
# Updated for SEO optimization deployment - Feb 27, 2026

echo "=========================================="
echo "Google Search Console URL Submission"
echo "Updated: February 27, 2026"
echo "=========================================="
echo ""

SUBMISSION_DATE="2026-02-27"

echo "HIGH PRIORITY - Submit These URLs First:"
echo "=========================================="
echo ""

echo "1. UPDATED Pages (SEO Title/Description Changes):"
echo "--------------------------------------------------"
echo ""
echo "   Things To Do (Updated):"
echo "   https://pagosaforestlodge.com/things-to-do/"
echo ""
echo "   Wolf Creek Comparison (New Title):"
echo "   https://pagosaforestlodge.com/blog/wolf-creek-vs-colorado-resorts-comparison/"
echo ""
echo "   Powder Day Strategy (New Title):"
echo "   https://pagosaforestlodge.com/blog/wolf-creek-powder-day-strategy-guide/"
echo ""
echo "   Wolf Creek Ski Guide (New Title):"
echo "   https://pagosaforestlodge.com/blog/wolf-creek-ski-resort-guide/"
echo ""
echo "   Altitude Sickness Guide (New Title):"
echo "   https://pagosaforestlodge.com/blog/altitude-sickness-pagosa-springs-guide/"
echo ""
echo "   Weekend Guide (New Title):"
echo "   https://pagosaforestlodge.com/blog/weekend-guide-pagosa-springs/"
echo ""
echo "   Off-Roading Guide (New Title):"
echo "   https://pagosaforestlodge.com/blog/off-roading-4x4-pagosa-springs/"
echo ""
echo "   Family Vacation Planner (New Title):"
echo "   https://pagosaforestlodge.com/blog/family-vacation-planner-pagosa-springs/"
echo ""
echo "   Restaurants Guide (Updated Year):"
echo "   https://pagosaforestlodge.com/blog/restaurants-pagosa-springs/"
echo ""
echo "   Annual Events (New Title):"
echo "   https://pagosaforestlodge.com/blog/annual-events-pagosa-springs/"
echo ""
echo "   Cabins vs Hotels (New Title):"
echo "   https://pagosaforestlodge.com/blog/pagosa-springs-cabins-vs-hotels-comparison/"
echo ""

echo ""
echo "2. NEW Blog Posts (Content Gap Fills):"
echo "----------------------------------------"
echo ""
echo "   Best Cabins in Pagosa Springs:"
echo "   https://pagosaforestlodge.com/blog/best-cabins-pagosa-springs-vacation-rentals/"
echo ""
echo "   Pet-Friendly Things to Do:"
echo "   https://pagosaforestlodge.com/blog/pet-friendly-things-to-do-pagosa-springs/"
echo ""
echo "   Photography Spots:"
echo "   https://pagosaforestlodge.com/blog/pagosa-springs-photography-spots-instagram/"
echo ""

echo ""
echo "3. EXISTING High-Value Posts (Verify Indexed):"
echo "------------------------------------------------"
echo ""
echo "   Kids Activities Guide:"
echo "   https://pagosaforestlodge.com/blog/best-things-to-do-pagosa-springs-kids-2026/"
echo ""
echo "   Hot Springs Guide:"
echo "   https://pagosaforestlodge.com/blog/hot-springs-pagosa-guide/"
echo ""
echo "   3-Day Itinerary:"
echo "   https://pagosaforestlodge.com/blog/3-day-itinerary-pagosa-springs/"
echo ""
echo "   Spring Skiing Guide:"
echo "   https://pagosaforestlodge.com/blog/spring-skiing-wolf-creek-march-april-guide/"
echo ""
echo "   Ice Skating Guide:"
echo "   https://pagosaforestlodge.com/blog/ice-skating-pagosa-springs-guide-2026/"
echo ""
echo "   Tours & Excursions:"
echo "   https://pagosaforestlodge.com/blog/pagosa-springs-tours-excursions-guide-2026/"
echo ""

echo ""
echo "=========================================="
echo "SUBMISSION METHODS"
echo "=========================================="
echo ""

echo "Option 1: Google Search Console Web Interface"
echo "----------------------------------------------"
echo "1. Visit: https://search.google.com/search-console"
echo "2. Select property: pagosaforestlodge.com"
echo "3. Go to 'URL Inspection' in left sidebar"
echo "4. Enter each URL above"
echo "5. Click 'Request Indexing' for each"
echo ""

echo "Option 2: Bulk URL Inspection (Recommended)"
echo "--------------------------------------------"
echo "Visit: https://search.google.com/search-console/inspections"
echo "Paste multiple URLs (one per line) for batch processing"
echo ""

echo ""
echo "=========================================="
echo "SITEMAP SUBMISSION"
echo "=========================================="
echo ""
echo "CRITICAL: Resubmit your sitemap to ensure all 49 URLs are discovered:"
echo ""
echo "1. Visit: https://search.google.com/search-console/sitemaps"
echo "2. Select property: pagosaforestlodge.com"
echo "3. Click 'Add a new sitemap'"
echo "4. Enter: https://pagosaforestlodge.com/sitemap.xml"
echo "5. Click 'Submit'"
echo ""
echo "Direct link:"
echo "https://search.google.com/search-console/sitemaps?resource_id=https://pagosaforestlodge.com/"
echo ""

echo ""
echo "=========================================="
echo "URL INSPECTION DIRECT LINKS"
echo "=========================================="
echo ""
echo "Click these links (requires GSC login):"
echo ""
echo "Sitemap:"
echo "https://search.google.com/search-console/sitemaps?resource_id=https://pagosaforestlodge.com/"
echo ""
echo "Things To Do:"
echo "https://search.google.com/search-console/inspect?resource_id=https://pagosaforestlodge.com/&id=https://pagosaforestlodge.com/things-to-do/"
echo ""
echo "Best Cabins:"
echo "https://search.google.com/search-console/inspect?resource_id=https://pagosaforestlodge.com/&id=https://pagosaforestlodge.com/blog/best-cabins-pagosa-springs-vacation-rentals/"
echo ""
echo "Pet-Friendly Guide:"
echo "https://search.google.com/search-console/inspect?resource_id=https://pagosaforestlodge.com/&id=https://pagosaforestlodge.com/blog/pet-friendly-things-to-do-pagosa-springs/"
echo ""
echo "Photography Spots:"
echo "https://search.google.com/search-console/inspect?resource_id=https://pagosaforestlodge.com/&id=https://pagosaforestlodge.com/blog/pagosa-springs-photography-spots-instagram/"
echo ""

echo ""
echo "=========================================="
echo "EXPECTED TIMELINE"
echo "=========================================="
echo ""
echo "• Indexing (new posts): 1-3 days"
echo "• Re-indexing (updated posts): 2-5 days"
echo "• Ranking changes: 2-4 weeks"
echo "• Traffic impact: 4-8 weeks"
echo ""

echo ""
echo "=========================================="
echo "MONITORING"
echo "=========================================="
echo ""
echo "Track progress in GSC:"
echo "• Coverage Report: Check for indexing errors"
echo "• Performance Report: Monitor CTR improvements"
echo "• URL Inspection: Verify individual pages"
echo ""
echo "Daily SEO Report runs at 9:00 AM MT"
echo "Check: ~/.openclaw-pfl/workspace/scripts/search-console/"
echo ""
